source 'https://rubygems.org'

gem 'bundler'
gem 'rake'
gem 'hanami'
gem 'hanami-model'


gem 'pg'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'pry-byebug'
end

group :production do
  # gem 'puma'
end
