# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30a3880728310f460773d8d8f184d699287dfae648eaa1b5f5e2ef5d32a5e601a6f658ff86ec2b3e2fc2f57e6e9e2cea4fa23f60046352fdc891603baa5bee99

test:
  secret_key_base: 8903c687fc88d33fd576178db0f6c1bad4c6ecb9a27b3b71f7e08c36711fceb98a743146e9417253affc331afa2bef219dcbebe85fb561d9432634786c07825a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
